name: cnr Deploy to Databricks
on:
  workflow_dispatch: {}
  # TODO confirm that we can get commit SHA
  # TODO this is only here for temporary testing. upon merge to master, use workflow_dispatch to do manual triggers:
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  pull_request:
    types: [ closed, synchronize ]

jobs:

  get-sha:
    uses: ./.github/workflows/get-sha.yml
  
  follow-up:
    needs: [ get-sha ]
    run: echo ${{ needs.get-sha.outputs.sha }}
